// Niş Ürün Veritabanı
// Tüm veriler gerçek pazar araştırmalarına dayalı örnek verilerdir.
// Fiyatlar TL cinsindendir, arama hacimleri Türkiye için tahminidir.
// niş puanı `calculateNicheScore` fonksiyonu ile otomatik hesaplanır.

import { NicheProduct } from './types';
import { calculateNicheScore } from './niche-algorithm';

const rawProducts: Omit<NicheProduct, 'nicheScore'>[] = [
  // ============ EV & YAŞAM ============
  {
    id: 'ev-001',
    name: 'Silikon Mutfak Tezgahı Koruyucu Minder',
    category: 'Ev & Yaşam',
    subCategory: 'Mutfak Gereçleri',
    costPrice: 27,
    sellPrice: 129,
    profitMargin: 79,
    competitorCount: 4,
    monthlySearchVolume: 4200,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    sourceUrl: 'https://www.trendyol.com',
    tags: ['mutfak', 'pratik', 'trend', 'hediyelik'],
    description: 'Tezgah ile ocak arasına yerleştirilen, yağ ve kir sıçramasını engelleyen katlanabilir silikon bariyer. Temizliği çok kolay.',
    supplierTip: 'Alibaba/Taobao\'da tanesi 8-15 TL\'ye bulunur. Minimum 50 adet siparişle birim maliyet düşer.',
  },
  {
    id: 'ev-002',
    name: 'Manyetik Sineklik (Kendinden Kapanan)',
    category: 'Ev & Yaşam',
    subCategory: 'Dekorasyon',
    costPrice: 35,
    sellPrice: 149,
    profitMargin: 76,
    competitorCount: 7,
    monthlySearchVolume: 8900,
    trend: 'stable',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Amazon / Trendyol',
    sourceUrl: 'https://www.trendyol.com',
    tags: ['sineklik', 'yaz', 'pratik', 'montajsız'],
    description: 'Ortadan mıknatıslı, kendiliğinden kapanan sineklik. Yaz aylarında patlama yapar.',
    supplierTip: 'Yerli üreticilerden toptan 25-35 TL. Çin\'den ithal ederseniz 12-20 TL.',
  },
  {
    id: 'ev-003',
    name: 'Akıllı LED Şerit (Wi-Fi + Alexa Uyumlu)',
    category: 'Ev & Yaşam',
    subCategory: 'Aydınlatma',
    costPrice: 65,
    sellPrice: 249,
    profitMargin: 74,
    competitorCount: 5,
    monthlySearchVolume: 6300,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    sourceUrl: 'https://www.hepsiburada.com',
    tags: ['led', 'akıllı ev', 'dekorasyon', 'teknoloji'],
    description: 'Wi-Fi bağlantılı, Alexa ve Google Home ile kontrol edilebilen RGB LED şerit. 5 metre.',
    supplierTip: 'Alibaba\'da 5 metrelik set 25-40 TL. CE belgeli olmasına dikkat edin.',
  },
  {
    id: 'ev-004',
    name: 'Balkon Katlanır Kurutmalık (Duvara Monte)',
    category: 'Ev & Yaşam',
    subCategory: 'Banyo',
    costPrice: 80,
    sellPrice: 289,
    profitMargin: 72,
    competitorCount: 3,
    monthlySearchVolume: 2800,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / N11',
    tags: ['balkon', 'kurutmalık', 'tasarruf', 'katlanabilir'],
    description: 'Duvara monte, kullanılmadığında katlanan alüminyum kurutmalık. Küçük balkonlar için ideal.',
    supplierTip: 'Yerli alüminyum atölyelerine özel üretim yaptırabilirsiniz. Toptan 60-70 TL.',
  },
  {
    id: 'ev-005',
    name: 'Bambu Banyo Rafı (Su Geçirmez)',
    category: 'Ev & Yaşam',
    subCategory: 'Banyo',
    costPrice: 45,
    sellPrice: 189,
    profitMargin: 76,
    competitorCount: 6,
    monthlySearchVolume: 3500,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['banyo', 'bambu', 'organizasyon', 'doğal'],
    description: 'Su geçirmez bambudan yapılmış, 3 katlı banyo rafı. Banyo dekorasyonunda trend.',
    supplierTip: 'Bambu ürünleri Vietnam ve Endonezya\'dan uygun fiyata ithal edilebilir.',
  },

  // ============ ANNE & BEBEK ============
  {
    id: 'bebek-001',
    name: 'Silikon Bebek Mama Kaşığı Seti (Isıya Duyarlı)',
    category: 'Anne & Bebek',
    subCategory: 'Beslenme',
    costPrice: 18,
    sellPrice: 89,
    profitMargin: 80,
    competitorCount: 5,
    monthlySearchVolume: 5100,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Anne Bebek Siteleri',
    tags: ['bebek', 'beslenme', 'silikon', 'güvenli'],
    description: 'Isıya duyarlı uçlarıyla mama sıcaklığını gösteren silikon kaşık seti. BPA içermez.',
    supplierTip: 'Alibaba\'da 6\'lı seti 5-8 TL. CE ve FDA sertifikalı tedarikçi seçin.',
  },
  {
    id: 'bebek-002',
    name: 'Montessori Ahşap Duyu Panosu (Meşgul Tahta)',
    category: 'Anne & Bebek',
    subCategory: 'Eğitici Materyal',
    costPrice: 65,
    sellPrice: 279,
    profitMargin: 77,
    competitorCount: 8,
    monthlySearchVolume: 7200,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / Etsy tarzı butik siteler',
    tags: ['montessori', 'eğitici', 'ahşap', 'okul öncesi'],
    description: 'Çocukların ince motor becerilerini geliştiren, üzerinde anahtar, fermuar, priz gibi objeler bulunan ahşap pano.',
    supplierTip: 'Yerli marangoz atölyelerine yaptırabilir veya kendiniz üretip kişiselleştirebilirsiniz.',
  },
  {
    id: 'bebek-003',
    name: 'Bebek Arabası Organizer (Geniş Cepli)',
    category: 'Anne & Bebek',
    subCategory: 'Bebek Odası',
    costPrice: 29,
    sellPrice: 119,
    profitMargin: 76,
    competitorCount: 6,
    monthlySearchVolume: 3800,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['bebek arabası', 'organizer', 'anne', 'pratik'],
    description: 'Bebek arabasına takılan, termos, biberon ve telefon için cepleri olan organizer çanta.',
    supplierTip: 'Çin\'den su geçirmez kumaş modelleri 10-18 TL. Toptan alımda nakliye optimize edilmeli.',
  },

  // ============ SPOR & OUTDOOR ============
  {
    id: 'spor-001',
    name: 'Katlanabilir Silikon Kamp Seti (Tabak + Bardak + Çatal)',
    category: 'Spor & Outdoor',
    subCategory: 'Kamp',
    costPrice: 35,
    sellPrice: 159,
    profitMargin: 78,
    competitorCount: 3,
    monthlySearchVolume: 5500,
    trend: 'rising',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Decathlon muadili',
    tags: ['kamp', 'katlanabilir', 'silikon', 'doğa'],
    description: 'Katlanabilir silikon kamp tabak, bardak ve çatal-bıçak seti. Hafif ve taşınabilir.',
    supplierTip: 'Alibaba\'da 3\'lü set 8-15 TL. CE belgeli ürün tercih edin.',
  },
  {
    id: 'spor-002',
    name: 'Ayarlanabilir Hamstring ve Kalça Egzersiz Aleti',
    category: 'Spor & Outdoor',
    subCategory: 'Fitness',
    costPrice: 55,
    sellPrice: 249,
    profitMargin: 78,
    competitorCount: 2,
    monthlySearchVolume: 3100,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Amazon / Trendyol',
    tags: ['fitness', 'ev sporu', 'bacak', 'kalça'],
    description: 'Evde hamstring ve kalça kaslarını çalıştırmaya yarayan kompakt egzersiz aleti.',
    supplierTip: 'Spor ekipmanı toptancılarından 40-55 TL. Özel etiketle satabilirsiniz.',
  },
  {
    id: 'spor-003',
    name: 'Su Geçirmez Telefon Kılıfı (IPX8 Sertifikalı)',
    category: 'Spor & Outdoor',
    subCategory: 'Su Sporları',
    costPrice: 15,
    sellPrice: 79,
    profitMargin: 81,
    competitorCount: 12,
    monthlySearchVolume: 9400,
    trend: 'stable',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['telefon', 'su geçirmez', 'tatil', 'plaj'],
    description: 'IPX8 sertifikalı, deniz ve havuzda telefon kullanımını sağlayan su geçirmez kılıf.',
    supplierTip: 'Rekabet biraz yüksek. Paket içeriğine ek aksesuar koyarak farklılaşın.',
  },

  // ============ EVCİL HAYVAN ============
  {
    id: 'pet-001',
    name: 'Otomatik Kedi Mama Kabı (Mikroçipli)',
    category: 'Evcil Hayvan',
    subCategory: 'Kedi',
    costPrice: 120,
    sellPrice: 499,
    profitMargin: 76,
    competitorCount: 3,
    monthlySearchVolume: 4100,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / Amazon',
    tags: ['kedi', 'otomatik', 'mama', 'akıllı'],
    description: 'Mikroçipli mama kabı - sadece tasması takılı kedinin kabını açar, mamanın taze kalmasını sağlar.',
    supplierTip: 'Alibaba\'da 50-80 TL. Elektronik ürün olduğu için CE/ROHS belgesi şart.',
  },
  {
    id: 'pet-002',
    name: 'Kedi Köpek Tüy Toplama Rulosu (Yıkanabilir)',
    category: 'Evcil Hayvan',
    subCategory: 'Köpek',
    costPrice: 22,
    sellPrice: 99,
    profitMargin: 78,
    competitorCount: 6,
    monthlySearchVolume: 6200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['tüy', 'temizlik', 'pratik', 'yıkanabilir'],
    description: 'Tekrar tekrar yıkanıp kullanılabilen, yapışkan bant gerektirmeyen tüy toplama rulosu.',
    supplierTip: 'Alibaba 8-12 TL toptan. Türkiye\'de bu ürünü satan az kişi var - fırsat!',
  },
  {
    id: 'pet-003',
    name: 'Akvaryum USB Hava Pompası (Sessiz)',
    category: 'Evcil Hayvan',
    subCategory: 'Akvaryum',
    costPrice: 35,
    sellPrice: 149,
    profitMargin: 76,
    competitorCount: 2,
    monthlySearchVolume: 1800,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['akvaryum', 'usb', 'sessiz', 'balık'],
    description: 'USB ile çalışan, elektrik kesintisinde powerbank ile devreye giren ultra sessiz hava pompası.',
    supplierTip: 'Çok az satıcı var, rakip 2-3 kişi. Alibaba\'da 12-18 TL. Hemen girilebilir.',
  },

  // ============ HOBİ & EL SANATLARI ============
  {
    id: 'hobi-001',
    name: 'Epoksi Reçine Takı Seti (Başlangıç Kiti)',
    category: 'Hobi & El Sanatları',
    subCategory: 'Takı Yapımı',
    costPrice: 55,
    sellPrice: 259,
    profitMargin: 79,
    competitorCount: 7,
    monthlySearchVolume: 8400,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['epoksi', 'takı', 'hobi', 'kendin yap'],
    description: 'Epoksi reçine, kalıplar, boyalar, kurutulmuş çiçekler içeren başlangıç seviyesi takı yapım kiti.',
    supplierTip: 'Yerli epoksi üreticilerinden toptan alım. Kalıpları Alibaba\'dan ucuza getirebilirsiniz.',
  },
  {
    id: 'hobi-002',
    name: '3D Ahşap Puzzle (Mimari Yapılar)',
    category: 'Hobi & El Sanatları',
    subCategory: 'Modelleme',
    costPrice: 40,
    sellPrice: 199,
    profitMargin: 80,
    competitorCount: 5,
    monthlySearchVolume: 4900,
    trend: 'rising',
    seasonality: 'winter',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['puzzle', 'ahşap', '3d', 'mimari'],
    description: 'Lazer kesim ahşap 3D yapboz. Saat kulesi, Eyfel, gemi gibi modeller.',
    supplierTip: 'Alibaba 15-25 TL arası. KDV ve gümrük hesaplanarak fiyatlandırma yapılmalı.',
  },

  // ============ TEKNOLOJİ & AKSESUAR ============
  {
    id: 'tech-001',
    name: 'Manyetik Telefon Tutucu Halka (Aksesuar Uyumlu)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Telefon',
    costPrice: 12,
    sellPrice: 69,
    profitMargin: 83,
    competitorCount: 15,
    monthlySearchVolume: 12500,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['telefon', 'tutucu', 'manyetik', 'aksesuar'],
    description: 'Telefon arkasına yapışan, araba tutucularıyla uyumlu manyetik halka. Düşmeye karşı güvenlik sağlar.',
    supplierTip: 'Yüksek rekabet var ama arama hacmi de çok yüksek. Farklı tasarımlarla öne çıkabilirsiniz.',
  },
  {
    id: 'tech-002',
    name: 'USB-C Manyetik Adaptör (9 Pin)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Kablo & Adaptör',
    costPrice: 18,
    sellPrice: 89,
    profitMargin: 80,
    competitorCount: 4,
    monthlySearchVolume: 5600,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['usb-c', 'manyetik', 'şarj', 'adaptör'],
    description: 'Telefonun USB-C girişine takılı kalan manyetik adaptör. Tek elle şarj bağlantısı sağlar.',
    supplierTip: 'Alibaba\'da 3-6 TL arası. 9 pinli modeller daha dayanıklı, mutlaka 9 pin seçin.',
  },
  {
    id: 'tech-003',
    name: 'Dizüstü Bilgisayar Yan Monitörü (Taşınabilir)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Bilgisayar',
    costPrice: 280,
    sellPrice: 899,
    profitMargin: 69,
    competitorCount: 2,
    monthlySearchVolume: 3800,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Amazon / Trendyol',
    tags: ['monitör', 'dizüstü', 'taşınabilir', 'verimlilik'],
    description: 'Dizüstü bilgisayara manyetik olarak yapışan, USB-C ile çalışan taşınabilir ikinci ekran. 14 inç.',
    supplierTip: 'Çok az satıcı var (2-3 kişi). Alibaba\'da 150-200 TL arası. Yüksek yatırım ama yüksek kâr.',
  },

  // ============ SAĞLIK & BAKIM ============
  {
    id: 'saglik-001',
    name: 'Gua Sha Masaj Taşı Seti (Doğal Yeşim)',
    category: 'Sağlık & Bakım',
    subCategory: 'Cilt Bakımı',
    costPrice: 22,
    sellPrice: 119,
    profitMargin: 82,
    competitorCount: 8,
    monthlySearchVolume: 7800,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Kozmetik Siteleri',
    tags: ['gua sha', 'yüz masajı', 'doğal', 'cilt'],
    description: 'Doğal yeşim taşından yapılmış, yüz masajı için gua sha seti. Lenf drenajını destekler.',
    supplierTip: 'Alibaba\'da doğal taş sertifikalı olanlar 8-15 TL. Sertifikasız taşlardan uzak durun.',
  },
  {
    id: 'saglik-002',
    name: 'USB Şarjlı Diş Taşı Temizleyici',
    category: 'Sağlık & Bakım',
    subCategory: 'Ağız Bakımı',
    costPrice: 38,
    sellPrice: 179,
    profitMargin: 79,
    competitorCount: 4,
    monthlySearchVolume: 6400,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['diş', 'temizlik', 'usb', 'kişisel bakım'],
    description: 'Evde profesyonel diş taşı temizliği yapabilen, USB şarjlı ultrasonik cihaz.',
    supplierTip: 'Medikal CE belgeli olması şart. Alibaba\'da 15-25 TL. Belgeleri kontrol edin.',
  },

  // ============ OTOMOTİV ============
  {
    id: 'oto-001',
    name: 'Araç İçi Manyetik Telefon Tutucu (Havalimanı Çıkışına)',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Aksesuar',
    costPrice: 22,
    sellPrice: 99,
    profitMargin: 78,
    competitorCount: 9,
    monthlySearchVolume: 9100,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['araba', 'telefon tutucu', 'manyetik', 'navigasyon'],
    description: 'Havalimanı çıkışına takılan, 360 derece dönebilen manyetik telefon tutucu.',
    supplierTip: 'Alibaba\'da 5-10 TL toptan. Kaliteli mıknatıs kullanan modelleri tercih edin.',
  },
  {
    id: 'oto-002',
    name: 'LED Kaput Altı Ambiyans Aydınlatma (Uzaktan Kumandalı)',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Tuning',
    costPrice: 45,
    sellPrice: 219,
    profitMargin: 79,
    competitorCount: 3,
    monthlySearchVolume: 3600,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['led', 'araba', 'ambiyans', 'tuning'],
    description: 'Uzaktan kumandalı, 16 renk değiştirebilen kaput altı LED aydınlatma kiti.',
    supplierTip: '12V LED kitler Alibaba\'da 18-30 TL. Montaj videosu ile birlikte satış yaparsanız fark yaratırsınız.',
  },

  // ============ PARTİ & ORGANİZASYON ============
  {
    id: 'parti-001',
    name: 'LED Balon Seti (Pil Dahil, 50 Adet)',
    category: 'Parti & Organizasyon',
    subCategory: 'Balon',
    costPrice: 40,
    sellPrice: 189,
    profitMargin: 79,
    competitorCount: 4,
    monthlySearchVolume: 5300,
    trend: 'rising',
    seasonality: 'holiday',
    difficulty: 'easy',
    source: 'Trendyol / Parti Malzemecileri',
    tags: ['balon', 'led', 'parti', 'doğum günü'],
    description: 'İçinde LED ışık olan, şişirildiğinde yanan 50 adet parti balonu. Piller balona dahil.',
    supplierTip: 'Alibaba\'da 50\'li set 15-25 TL. Doğum günü sezonunda stok tutun.',
  },

  // ============ KİTAP & KIRTASİYE ============
  {
    id: 'kitap-001',
    name: 'Akıllı Not Defteri (Yıkanabilir Sayfalar)',
    category: 'Kitap & Kırtasiye',
    subCategory: 'Defter',
    costPrice: 45,
    sellPrice: 199,
    profitMargin: 77,
    competitorCount: 3,
    monthlySearchVolume: 4600,
    trend: 'rising',
    seasonality: 'back-to-school',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['defter', 'yıkanabilir', 'akıllı', 'sürdürülebilir'],
    description: 'Özel kalemiyle yazılıp, ıslak bezle silinebilen, tekrar tekrar kullanılabilen akıllı not defteri.',
    supplierTip: 'Alibaba\'da 18-28 TL. Kendi markanızı bastırabilir, kurumsal hediye olarak da satabilirsiniz.',
  },
  {
    id: 'kitap-002',
    name: 'Roller Kalem Seti (12 Renk, Su Bazlı)',
    category: 'Kitap & Kırtasiye',
    subCategory: 'Kalem',
    costPrice: 28,
    sellPrice: 129,
    profitMargin: 78,
    competitorCount: 5,
    monthlySearchVolume: 5100,
    trend: 'stable',
    seasonality: 'back-to-school',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['kalem', 'renkli', 'su bazlı', 'hediyelik'],
    description: '12 renk su bazlı roller kalem seti. Not tutma, bullet journal ve scrapbooking için ideal.',
    supplierTip: 'Alibaba\'da 12\'li seti 8-15 TL. Okul döneminde stok patlaması yaşanır.',
  },

  // ============ YÜKSEK KÂR / DÜŞÜK REKABET ÖZEL ÜRÜNLER ============
  {
    id: 'ozel-001',
    name: 'Araç İçi Mini Buharlı Temizleyici',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Bakım',
    costPrice: 55,
    sellPrice: 299,
    profitMargin: 82,
    competitorCount: 2,
    monthlySearchVolume: 2900,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Amazon / N11',
    tags: ['temizlik', 'buhar', 'araba', 'detaylı temizlik'],
    description: 'Çakmaklıktan çalışan, araç içi detaylı buharlı temizlik cihazı. Koltuk ve halı temizliğinde etkili.',
    supplierTip: 'Sadece 2 rakip var. Alibaba\'da 25-35 TL. Kullanım videosuyla satışları katlayabilirsiniz.',
  },
  {
    id: 'ozel-002',
    name: 'Portatif Biyometrik Çanta Kilidi (Parmak İzi)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Giyilebilir',
    costPrice: 48,
    sellPrice: 259,
    profitMargin: 81,
    competitorCount: 1,
    monthlySearchVolume: 2200,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Amazon / Trendyol',
    tags: ['güvenlik', 'parmak izi', 'çanta', 'teknoloji'],
    description: 'USB şarjlı, parmak iziyle açılan portatif çanta kilidi. Seyahat ve spor çantaları için.',
    supplierTip: 'Türkiye\'de neredeyse hiç satıcı yok. Alibaba\'da 20-30 TL. İlk giren büyük avantaj yakalar.',
  },
  {
    id: 'ozel-003',
    name: 'Kablosuz Elektrikli Matkap Temizleme Fırçası Seti',
    category: 'Ev & Yaşam',
    subCategory: 'Organizasyon',
    costPrice: 42,
    sellPrice: 229,
    profitMargin: 82,
    competitorCount: 3,
    monthlySearchVolume: 3300,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['temizlik', 'elektrikli', 'fırça', 'pratik'],
    description: 'USB şarjlı, değiştirilebilir başlıklı elektrikli temizlik fırçası. Fayans, banyo ve mutfak için.',
    supplierTip: 'Alibaba\'da 15-22 TL set. Temizlik trendinde popüler - sosyal medyada viral olabilir.',
  },
  {
    id: 'ozel-004',
    name: 'Mıknatıslı Buzdolabı Beyaz Tahta (Esnek)',
    category: 'Ev & Yaşam',
    subCategory: 'Organizasyon',
    costPrice: 28,
    sellPrice: 139,
    profitMargin: 80,
    competitorCount: 2,
    monthlySearchVolume: 2400,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['buzdolabı', 'beyaz tahta', 'organizasyon', 'alışveriş listesi'],
    description: 'Buzdolabına yapışan esnek manyetik beyaz tahta. Kalemiyle birlikte gelir. Alışveriş listesi ve notlar için.',
    supplierTip: 'Sadece 1-2 rakip var. Alibaba\'da 8-15 TL. Kâr marjı çok yüksek, küçük ve hafif (kargo avantajı).',
  },

  // ============ EK ÜRÜNLER - EV & YAŞAM ============
  {
    id: 'ev-006',
    name: 'Silikon Buzdolabı Rafı (Genişletilebilir)',
    category: 'Ev & Yaşam',
    subCategory: 'Organizasyon',
    costPrice: 19,
    sellPrice: 89,
    profitMargin: 79,
    competitorCount: 5,
    monthlySearchVolume: 3600,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['buzdolabı', 'organizasyon', 'silikon', 'pratik'],
    description: 'Buzdolabı raflarını bölerek daha fazla alan yaratır. Genişletilebilir, kaymaz silikon yapı.',
    supplierTip: 'Alibaba\'da 5-10 TL. Çok hafif, kargo maliyeti düşük.',
  },
  {
    id: 'ev-007',
    name: 'Mikrodalga Temizleyici (Angry Mama)',
    category: 'Ev & Yaşam',
    subCategory: 'Mutfak Gereçleri',
    costPrice: 14,
    sellPrice: 69,
    profitMargin: 80,
    competitorCount: 3,
    monthlySearchVolume: 2100,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['mutfak', 'temizlik', 'mikrodalga', 'pratik'],
    description: 'Sirke ve su konularak mikrodalgada çalıştırılan, yağı gevşeten temizleyici figür.',
    supplierTip: 'Alibaba 3-6 TL. Viral ürün, sosyal medya reklamlarıyla iyi satar.',
  },
  {
    id: 'ev-008',
    name: 'Kablosuz Su Geçirmez LED Bahçe Işığı (4\'lü)',
    category: 'Ev & Yaşam',
    subCategory: 'Bahçe',
    costPrice: 48,
    sellPrice: 229,
    profitMargin: 79,
    competitorCount: 4,
    monthlySearchVolume: 4300,
    trend: 'rising',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['bahçe', 'led', 'güneş enerjisi', 'dekorasyon'],
    description: 'Güneş enerjili, su geçirmez, otomatik açılan bahçe LED ışıkları. 4 adet set.',
    supplierTip: 'Alibaba 4\'lü set 18-28 TL. Yaz sezonunda stok tutun.',
  },
  {
    id: 'ev-009',
    name: 'Kendinden Yapışkanlı Duvar Kağıdı (3D Tuğla Desen)',
    category: 'Ev & Yaşam',
    subCategory: 'Dekorasyon',
    costPrice: 32,
    sellPrice: 149,
    profitMargin: 78,
    competitorCount: 6,
    monthlySearchVolume: 7800,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['duvar kağıdı', 'dekorasyon', '3d', 'kendin yap'],
    description: 'Kendinden yapışkanlı, kolayca uygulanabilen 3D tuğla desenli duvar paneli. Su geçirmez.',
    supplierTip: 'Alibaba\'da metrekaresi 8-15 TL. Örnek parça gönderen tedarikçilerle çalışın.',
  },
  {
    id: 'ev-010',
    name: 'Silikon Buz Küpü (Tekrar Kullanılabilir)',
    category: 'Ev & Yaşam',
    subCategory: 'Mutfak Gereçleri',
    costPrice: 12,
    sellPrice: 59,
    profitMargin: 80,
    competitorCount: 4,
    monthlySearchVolume: 2900,
    trend: 'rising',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['mutfak', 'buz', 'yaz', 'silikon'],
    description: 'Paslanmaz çelik içli, tekrar kullanılabilir silikon buz küpleri. İçkiyi sulandırmaz.',
    supplierTip: 'Alibaba 6\'lı set 4-8 TL. Premium ambalajla kâr artırılabilir.',
  },
  {
    id: 'ev-011',
    name: 'Kablosuz Kapı Zili (Kendinden Yapışkanlı)',
    category: 'Ev & Yaşam',
    subCategory: 'Dekorasyon',
    costPrice: 42,
    sellPrice: 189,
    profitMargin: 78,
    competitorCount: 3,
    monthlySearchVolume: 5200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['kapı zili', 'kablosuz', 'pratik', 'ev'],
    description: 'Prizli alıcı ve kendinden yapışkanlı buton. 36 farklı melodi, 100m menzil.',
    supplierTip: 'Alibaba\'da 15-25 TL. CE belgeli ürün tercih edin.',
  },
  {
    id: 'ev-012',
    name: 'Banyo Lavabo Tıkanıklık Açıcı (Saç Yakalayıcı)',
    category: 'Ev & Yaşam',
    subCategory: 'Banyo',
    costPrice: 8,
    sellPrice: 49,
    profitMargin: 84,
    competitorCount: 2,
    monthlySearchVolume: 1800,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['banyo', 'temizlik', 'tıkanıklık', 'saç'],
    description: 'Lavabo giderine yerleştirilen, saçları ve kiri yakalayan silikon filtre.',
    supplierTip: 'Alibaba 1-3 TL. Çok düşük maliyet, yüksek kâr. Toplu satış ideal.',
  },

  // ============ EK ÜRÜNLER - ANNE & BEBEK ============
  {
    id: 'bebek-004',
    name: 'Bebek Emniyet Kemeri (Yatak / Koltuk)',
    category: 'Anne & Bebek',
    subCategory: 'Güvenlik',
    costPrice: 35,
    sellPrice: 159,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 3400,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['bebek', 'güvenlik', 'yatak', 'kemer'],
    description: 'Yatak veya koltuğa takılan, bebeğin düşmesini engelleyen yumuşak emniyet kemeri.',
    supplierTip: 'Alibaba 12-20 TL. Standartlara uygun, nefes alabilir kumaş seçin.',
  },
  {
    id: 'bebek-005',
    name: 'Silikon Bebek Diş Kaşıyıcı Eldiven',
    category: 'Anne & Bebek',
    subCategory: 'Oyuncak',
    costPrice: 16,
    sellPrice: 79,
    profitMargin: 80,
    competitorCount: 5,
    monthlySearchVolume: 4100,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Anne Bebek Siteleri',
    tags: ['bebek', 'diş kaşıyıcı', 'silikon', 'eldiven'],
    description: 'Bebeğin eline takılan, diş kaşıma ihtiyacını karşılayan BPA-free silikon eldiven.',
    supplierTip: 'Alibaba 3-6 TL. FDA onaylı olmalı. Hediye seti olarak paketlenebilir.',
  },
  {
    id: 'bebek-006',
    name: 'Taşınabilir Bebek Mama Isıtıcı (USB)',
    category: 'Anne & Bebek',
    subCategory: 'Beslenme',
    costPrice: 55,
    sellPrice: 249,
    profitMargin: 78,
    competitorCount: 2,
    monthlySearchVolume: 2600,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / Amazon',
    tags: ['bebek', 'mama', 'ısıtıcı', 'usb'],
    description: 'Powerbank ile çalışan, seyahatlerde biberon ısıtan taşınabilir ısıtıcı kılıf.',
    supplierTip: 'Alibaba 20-35 TL. Çok az rakip, fırsat ürünü.',
  },
  {
    id: 'bebek-007',
    name: 'Bebek Ayak İzi ve El İzi Mürekkepsiz Set',
    category: 'Anne & Bebek',
    subCategory: 'Bebek Odası',
    costPrice: 22,
    sellPrice: 99,
    profitMargin: 78,
    competitorCount: 3,
    monthlySearchVolume: 3200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hediyelik Siteler',
    tags: ['bebek', 'anı', 'hediye', 'iz'],
    description: 'Mürekkepsiz, bebeğin ayak ve el izini alarak anı oluşturan set. Temiz ve güvenli.',
    supplierTip: 'Alibaba 6-12 TL. Hediye paketi olarak satılabilir.',
  },

  // ============ EK ÜRÜNLER - SPOR & OUTDOOR ============
  {
    id: 'spor-004',
    name: 'Elastik Direnç Bandı Seti (5\'li + Taşıma Çantası)',
    category: 'Spor & Outdoor',
    subCategory: 'Fitness',
    costPrice: 28,
    sellPrice: 129,
    profitMargin: 78,
    competitorCount: 8,
    monthlySearchVolume: 9500,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['fitness', 'direnç bandı', 'ev sporu', 'set'],
    description: '5 farklı direnç seviyesinde lateks band seti. Kapı ankrajı ve taşıma çantası dahil.',
    supplierTip: 'Rekabet yüksek ama talep de yüksek. Farklı renk ve paketleme ile öne çıkın.',
  },
  {
    id: 'spor-005',
    name: 'Kamp Feneri (Solar + USB Şarjlı)',
    category: 'Spor & Outdoor',
    subCategory: 'Kamp',
    costPrice: 38,
    sellPrice: 179,
    profitMargin: 79,
    competitorCount: 4,
    monthlySearchVolume: 4800,
    trend: 'rising',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['kamp', 'fener', 'güneş enerjisi', 'outdoor'],
    description: 'Güneş enerjili ve USB şarjlı, 3 modlu kamp feneri. Acil durum lambası olarak da kullanılır.',
    supplierTip: 'Alibaba 15-25 TL. Yaz sezonunda stok tutun.',
  },
  {
    id: 'spor-006',
    name: 'Bisiklet Telefon Tutucu (Gidon İçin)',
    category: 'Spor & Outdoor',
    subCategory: 'Bisiklet',
    costPrice: 18,
    sellPrice: 89,
    profitMargin: 80,
    competitorCount: 6,
    monthlySearchVolume: 6700,
    trend: 'stable',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['bisiklet', 'telefon', 'tutucu', 'spor'],
    description: 'Gidonlara takılan, 360 derece dönebilen, darbeye dayanıklı telefon tutucu.',
    supplierTip: 'Alibaba 6-12 TL. Alüminyum gövdeli modeller daha iyi satar.',
  },
  {
    id: 'spor-007',
    name: 'Koşu Telefon Kemeri (Bel Çantası)',
    category: 'Spor & Outdoor',
    subCategory: 'Koşu',
    costPrice: 24,
    sellPrice: 109,
    profitMargin: 78,
    competitorCount: 5,
    monthlySearchVolume: 3900,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['koşu', 'bel çantası', 'telefon', 'spor'],
    description: 'Koşu ve yürüyüşte telefonu taşımaya yarayan, ter geçirmez bel kemeri.',
    supplierTip: 'Alibaba 8-15 TL. Yansıtıcı şeritli modeller tercih edilir.',
  },
  {
    id: 'spor-008',
    name: 'Şişme Yüzme Yeleği (Yetişkin / Çocuk)',
    category: 'Spor & Outdoor',
    subCategory: 'Su Sporları',
    costPrice: 45,
    sellPrice: 199,
    profitMargin: 77,
    competitorCount: 3,
    monthlySearchVolume: 5600,
    trend: 'stable',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['yüzme', 'yelek', 'yaz', 'deniz'],
    description: 'Hızlı şişirilebilen, CE onaylı yüzme yeleği. Yetişkin ve çocuk boyları.',
    supplierTip: 'Alibaba 18-28 TL. CE belgesi şart. Yaz sezonunda patlar.',
  },

  // ============ EK ÜRÜNLER - EVCİL HAYVAN ============
  {
    id: 'pet-004',
    name: 'Kedi Tırmalama Tahtası (Karton + Kedi Otu)',
    category: 'Evcil Hayvan',
    subCategory: 'Kedi',
    costPrice: 22,
    sellPrice: 99,
    profitMargin: 78,
    competitorCount: 5,
    monthlySearchVolume: 7200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['kedi', 'tırmalama', 'karton', 'kedi otu'],
    description: 'Kedi otu içeren, dayanıklı karton tırmalama tahtası. Mobilyaları korur.',
    supplierTip: 'Yerli karton üreticilerinden uygun fiyata yapılabilir. Kedi otu dahil edin.',
  },
  {
    id: 'pet-005',
    name: 'Köpek Su Şişesi (Yürüyüş İçin)',
    category: 'Evcil Hayvan',
    subCategory: 'Köpek',
    costPrice: 19,
    sellPrice: 89,
    profitMargin: 79,
    competitorCount: 4,
    monthlySearchVolume: 4600,
    trend: 'rising',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['köpek', 'su şişesi', 'yürüyüş', 'pratik'],
    description: 'Köpekler için taşınabilir, bardağa dönüşen su şişesi. Sızıntı yapmaz.',
    supplierTip: 'Alibaba 6-12 TL. Yaz aylarında talep artar.',
  },
  {
    id: 'pet-006',
    name: 'Kedi Pencere Oturmağı (Vantuzlu)',
    category: 'Evcil Hayvan',
    subCategory: 'Kedi',
    costPrice: 55,
    sellPrice: 249,
    profitMargin: 78,
    competitorCount: 3,
    monthlySearchVolume: 3800,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['kedi', 'pencere', 'yatak', 'vantuz'],
    description: 'Pencere camına vantuzla tutturulan, güneşlenmek için kedi yatağı.',
    supplierTip: 'Alibaba 20-35 TL. Sağlam vantuz ve halat önemli.',
  },
  {
    id: 'pet-007',
    name: 'Akvaryum Bitki Seti (Yapay, Işıltılı)',
    category: 'Evcil Hayvan',
    subCategory: 'Akvaryum',
    costPrice: 15,
    sellPrice: 69,
    profitMargin: 78,
    competitorCount: 2,
    monthlySearchVolume: 2100,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['akvaryum', 'bitki', 'yapay', 'dekorasyon'],
    description: 'Akvaryum için parlak renkli yapay bitki seti. Balıklar için güvenli malzeme.',
    supplierTip: 'Alibaba 5-10 TL set. Düşük maliyet, iyi kâr.',
  },

  // ============ EK ÜRÜNLER - HOBİ & EL SANATLARI ============
  {
    id: 'hobi-003',
    name: 'Elmas Mozaik Boyama Seti (40x50 cm)',
    category: 'Hobi & El Sanatları',
    subCategory: 'Resim',
    costPrice: 35,
    sellPrice: 159,
    profitMargin: 78,
    competitorCount: 6,
    monthlySearchVolume: 5800,
    trend: 'stable',
    seasonality: 'winter',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['hobi', 'mozaik', 'boyama', 'el sanatı'],
    description: 'Küçük elmas taşlarla yapılan, stres azaltıcı mozaik boyama seti.',
    supplierTip: 'Alibaba 12-20 TL. Kış aylarında daha çok satar.',
  },
  {
    id: 'hobi-004',
    name: 'Deri El İşi Seti (Kendin Yap Çanta)',
    category: 'Hobi & El Sanatları',
    subCategory: 'DIY Kitleri',
    costPrice: 42,
    sellPrice: 189,
    profitMargin: 78,
    competitorCount: 2,
    monthlySearchVolume: 2400,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / Etsy tarzı siteler',
    tags: ['deri', 'kendin yap', 'çanta', 'hobi'],
    description: 'Kendi deri çantasını dikmek için iğne, ip, malzeme ve şablon seti.',
    supplierTip: 'Alibaba 15-25 TL. Butik hediye olarak konumlandırılabilir.',
  },
  {
    id: 'hobi-005',
    name: 'Örgü Makinesi (Elle Çalışan)',
    category: 'Hobi & El Sanatları',
    subCategory: 'Örgü',
    costPrice: 65,
    sellPrice: 289,
    profitMargin: 77,
    competitorCount: 3,
    monthlySearchVolume: 4100,
    trend: 'rising',
    seasonality: 'winter',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['örgü', 'makine', 'kış', 'hobi'],
    description: 'Elle çalışan, hızlı örgü yapmayı sağlayan kompakt örgü makinesi.',
    supplierTip: 'Alibaba 25-40 TL. Kış sezonunda stok tutun.',
  },
  {
    id: 'hobi-006',
    name: 'Takı Yapımı Boncuk Seti (500+ Parça)',
    category: 'Hobi & El Sanatları',
    subCategory: 'Takı Yapımı',
    costPrice: 25,
    sellPrice: 119,
    profitMargin: 79,
    competitorCount: 5,
    monthlySearchVolume: 5100,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['takı', 'boncuk', 'hobi', 'set'],
    description: '500+ parça boncuk, kordon ve aksesuar içeren takı yapım seti.',
    supplierTip: 'Alibaba 8-15 TL. Renkli organizatör kutusuyla fark yaratın.',
  },

  // ============ EK ÜRÜNLER - TEKNOLOJİ & AKSESUAR ============
  {
    id: 'tech-004',
    name: 'Telefon Kamera Lens Seti (Makro + Balık Gözü)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Telefon',
    costPrice: 32,
    sellPrice: 149,
    profitMargin: 78,
    competitorCount: 5,
    monthlySearchVolume: 6200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['telefon', 'lens', 'fotoğraf', 'aksesuar'],
    description: 'Telefona takılan makro, balık gözü ve geniş açı lens seti. Klipsli tasarım.',
    supplierTip: 'Alibaba 10-18 TL. Lens kalitesi önemli, örnek isteyin.',
  },
  {
    id: 'tech-005',
    name: 'Laptop Standı (Alüminyum, Katlanabilir)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Bilgisayar',
    costPrice: 55,
    sellPrice: 249,
    profitMargin: 78,
    competitorCount: 7,
    monthlySearchVolume: 8900,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['laptop', 'stand', 'alüminyum', 'ofis'],
    description: 'Ergonomik, 6 kademeli, katlanabilir alüminyum laptop standı. Soğutmayı destekler.',
    supplierTip: 'Alibaba 20-35 TL. Hafif alüminyum gövde tercih edin.',
  },
  {
    id: 'tech-006',
    name: 'Kablosuz Şarj Standı (Telefon + AirPods)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Telefon',
    costPrice: 38,
    sellPrice: 179,
    profitMargin: 79,
    competitorCount: 6,
    monthlySearchVolume: 7400,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['şarj', 'kablosuz', 'telefon', 'airpods'],
    description: 'Telefon ve AirPods\'u aynı anda şarj eden 2\'li kablosuz şarj standı.',
    supplierTip: 'Alibaba 15-25 TL. Qi sertifikalı olmasına dikkat edin.',
  },
  {
    id: 'tech-007',
    name: 'RGB Oyun Mouse Pad (Büyük Boy)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Oyun',
    costPrice: 42,
    sellPrice: 189,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 4800,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['oyun', 'mouse pad', 'rgb', 'gamer'],
    description: 'LED ışıklı, kaymaz tabanlı, büyük boy RGB oyun mouse pad\'i.',
    supplierTip: 'Alibaba 15-25 TL. Gamer kitleye yönelik pazarlama yapın.',
  },
  {
    id: 'tech-008',
    name: 'Bluetooth Uzaktan Deklanşör (Selfie)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Telefon',
    costPrice: 12,
    sellPrice: 59,
    profitMargin: 80,
    competitorCount: 8,
    monthlySearchVolume: 3600,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['selfie', 'bluetooth', 'kumanda', 'telefon'],
    description: 'Telefon kamerasını uzaktan tetikleyen mini Bluetooth kumanda. Selfie ve video çekimleri için.',
    supplierTip: 'Alibaba 3-6 TL. Hediye seti olarak satılabilir.',
  },

  // ============ EK ÜRÜNLER - SAĞLIK & BAKIM ============
  {
    id: 'saglik-003',
    name: 'Silikon Yüz Temizleme Fırçası (Elektrikli)',
    category: 'Sağlık & Bakım',
    subCategory: 'Cilt Bakımı',
    costPrice: 35,
    sellPrice: 159,
    profitMargin: 78,
    competitorCount: 6,
    monthlySearchVolume: 6800,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Kozmetik Siteleri',
    tags: ['cilt bakımı', 'fırça', 'silikon', 'yüz'],
    description: 'Titreşimli, silikon kıllı yüz temizleme fırçası. Derinlemesine temizlik sağlar.',
    supplierTip: 'Alibaba 12-20 TL. Su geçirmez ve şarjlı modeller tercih edin.',
  },
  {
    id: 'saglik-004',
    name: 'Saç Dökülmesine Karşı Masaj Tarağı',
    category: 'Sağlık & Bakım',
    subCategory: 'Saç Bakımı',
    costPrice: 18,
    sellPrice: 89,
    profitMargin: 80,
    competitorCount: 4,
    monthlySearchVolume: 5200,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['saç', 'masaj', 'tarağı', 'dökülme'],
    description: 'Saç derisini kan dolaşımını artıran, yuvarlak uçlu masaj tarağı.',
    supplierTip: 'Alibaba 5-10 TL. Saç bakım seti içinde satılabilir.',
  },
  {
    id: 'saglik-005',
    name: 'Aromaterapi Uçucu Yağ Seti (6\'lı)',
    category: 'Sağlık & Bakım',
    subCategory: 'Aromaterapi',
    costPrice: 28,
    sellPrice: 129,
    profitMargin: 78,
    competitorCount: 5,
    monthlySearchVolume: 4300,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['aromaterapi', 'yağ', 'relax', 'set'],
    description: '6 farklı uçucu yağ içeren aromaterapi seti. Lavanta, nane, portakal vb.',
    supplierTip: 'Yerli üreticilerden toptan alım. Kaliteli şişe ve etiket önemli.',
  },
  {
    id: 'saglik-006',
    name: 'Masaj Topu Seti (3\'lü, Farklı Sertlik)',
    category: 'Sağlık & Bakım',
    subCategory: 'Masaj',
    costPrice: 22,
    sellPrice: 99,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 3900,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['masaj', 'top', 'fitness', 'rahatlama'],
    description: 'Kas gevşetmeye yardımcı, 3 farklı sertlikte masaj topu seti.',
    supplierTip: 'Alibaba 7-12 TL. Sporcu ve ofis çalışanlarına hedefleyin.',
  },

  // ============ EK ÜRÜNLER - OTOMOTİV ============
  {
    id: 'oto-003',
    name: 'Araç İçi Çöp Kovası (Kapaklı)',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Aksesuar',
    costPrice: 16,
    sellPrice: 79,
    profitMargin: 80,
    competitorCount: 5,
    monthlySearchVolume: 4700,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['araba', 'çöp', 'organizasyon', 'pratik'],
    description: 'Kapaklı, su geçirmez, araç içi çöp kutusu. Torpido veya arka koltuğa takılabilir.',
    supplierTip: 'Alibaba 5-10 TL. Silikon veya plastik modeller mevcut.',
  },
  {
    id: 'oto-004',
    name: 'Motosiklet Telefon Tutucu (Ayna Bağlantılı)',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Motosiklet Ekipmanı',
    costPrice: 32,
    sellPrice: 149,
    profitMargin: 78,
    competitorCount: 3,
    monthlySearchVolume: 3400,
    trend: 'rising',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['motosiklet', 'telefon', 'tutucu', 'navigasyon'],
    description: 'Motosiklet aynasına takılan, darbeye dayanıklı telefon tutucu. Su geçirmez kılıf dahil.',
    supplierTip: 'Alibaba 12-20 TL. Yaz sezonunda motosiklet aksesuarları artar.',
  },
  {
    id: 'oto-005',
    name: 'Araç Koltuk Boyun Yastığı (Bellek Köpüğü)',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Aksesuar',
    costPrice: 28,
    sellPrice: 129,
    profitMargin: 78,
    competitorCount: 6,
    monthlySearchVolume: 5800,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['araba', 'koltuk', 'yastık', 'konfor'],
    description: 'Bellek köpüğünden, boyun destekli araç koltuk yastığı. Uzun yolculuklar için ideal.',
    supplierTip: 'Alibaba 10-18 TL. Premium kumaşla fark yaratabilirsiniz.',
  },
  {
    id: 'oto-006',
    name: 'Araç İçi Mini Elektrikli Süpürge',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Bakım',
    costPrice: 48,
    sellPrice: 219,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 6100,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['araba', 'süpürge', 'temizlik', 'elektrikli'],
    description: 'Çakmaklıktan çalışan, kompakt araç içi elektrikli süpürge. Farklı başlıklar dahil.',
    supplierTip: 'Alibaba 18-30 TL. Güçlü motorlu modeller tercih edin.',
  },

  // ============ EK ÜRÜNLER - PARTİ & ORGANİZASYON ============
  {
    id: 'parti-002',
    name: 'Kişiselleştirilebilir Doğum Günü Balonu (İsimli)',
    category: 'Parti & Organizasyon',
    subCategory: 'Balon',
    costPrice: 25,
    sellPrice: 119,
    profitMargin: 79,
    competitorCount: 3,
    monthlySearchVolume: 4100,
    trend: 'rising',
    seasonality: 'holiday',
    difficulty: 'easy',
    source: 'Trendyol / Parti Malzemecileri',
    tags: ['doğum günü', 'balon', 'kişiselleştirme', 'hediye'],
    description: 'İsim yazılabilen, özel günler için kişiselleştirilebilir folyo balon seti.',
    supplierTip: 'Alibaba 8-15 TL. Kişiselleştirme hizmetiyle kâr artırılabilir.',
  },
  {
    id: 'parti-003',
    name: 'Parti Fotoğraf Çerçevesi (Selfie Frame)',
    category: 'Parti & Organizasyon',
    subCategory: 'Parti Malzemeleri',
    costPrice: 22,
    sellPrice: 99,
    profitMargin: 78,
    competitorCount: 2,
    monthlySearchVolume: 2800,
    trend: 'stable',
    seasonality: 'holiday',
    difficulty: 'easy',
    source: 'Trendyol / Etsy tarzı siteler',
    tags: ['parti', 'fotoğraf', 'çerçeve', 'selfie'],
    description: 'Partilerde fotoğraf çekimi için kullanılan, kişiselleştirilebilir selfie çerçevesi.',
    supplierTip: 'Yerli baskıcılarla çalışın. Karton maliyeti düşük, kâr yüksek.',
  },
  {
    id: 'parti-004',
    name: 'Hediye Paketleme Kağıdı Seti (10\'lu)',
    category: 'Parti & Organizasyon',
    subCategory: 'Hediye Paketleme',
    costPrice: 18,
    sellPrice: 89,
    profitMargin: 80,
    competitorCount: 4,
    monthlySearchVolume: 3600,
    trend: 'stable',
    seasonality: 'holiday',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['hediye', 'paketleme', 'kağıt', 'set'],
    description: '10 farklı desende hediye paketleme kağıdı seti. Kurdele ve etiket dahil.',
    supplierTip: 'Alibaba 6-12 TL. Sevgililer Günü ve yılbaşında stok tutun.',
  },

  // ============ EK ÜRÜNLER - KIRTASİYE ============
  {
    id: 'kitap-003',
    name: 'Akıllı Planlayıcı Defter (Hedef Takvimli)',
    category: 'Kitap & Kırtasiye',
    subCategory: 'Planlayıcı',
    costPrice: 32,
    sellPrice: 149,
    profitMargin: 78,
    competitorCount: 5,
    monthlySearchVolume: 4700,
    trend: 'rising',
    seasonality: 'back-to-school',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['planlayıcı', 'defter', 'hedef', 'verimlilik'],
    description: 'Günlük hedef, alışkanlık takibi ve not alma için akıllı planlayıcı defter.',
    supplierTip: 'Alibaba 12-20 TL. Kendi markanızı bastırabilirsiniz.',
  },
  {
    id: 'kitap-004',
    name: 'Sanatsal Eskiz Defteri (A5, 120 gsm)',
    category: 'Kitap & Kırtasiye',
    subCategory: 'Sanatsal Malzeme',
    costPrice: 24,
    sellPrice: 109,
    profitMargin: 78,
    competitorCount: 3,
    monthlySearchVolume: 3100,
    trend: 'stable',
    seasonality: 'back-to-school',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['defter', 'eskiz', 'sanat', 'çizim'],
    description: 'Kalın kağıtlı, su bazlı boya ve kalem için uygun A5 sanatsal eskiz defteri.',
    supplierTip: 'Alibaba 8-15 TL. Sanatçı ve öğrenci kitlesine hedefleyin.',
  },
  {
    id: 'kitap-005',
    name: 'Masaüstü Düzenleyici (Ahşap)',
    category: 'Kitap & Kırtasiye',
    subCategory: 'Kalem',
    costPrice: 38,
    sellPrice: 169,
    profitMargin: 77,
    competitorCount: 4,
    monthlySearchVolume: 4200,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['masaüstü', 'organizer', 'ahşap', 'ofis'],
    description: 'Kalem, telefon ve not tutucu bölmeleri olan ahşap masaüstü düzenleyici.',
    supplierTip: 'Yerli ahşap atölyelerinden 15-25 TL. Kurumsal hediye olarak satılabilir.',
  },

  // ============ EK ÜRÜNLER - YÜKSEK KÂR / DÜŞÜK REKABET ============
  {
    id: 'ozel-005',
    name: 'Akıllı Çöp Kutusu Kapağı (Sensörlü)',
    category: 'Ev & Yaşam',
    subCategory: 'Organizasyon',
    costPrice: 65,
    sellPrice: 299,
    profitMargin: 78,
    competitorCount: 2,
    monthlySearchVolume: 3500,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / Amazon',
    tags: ['çöp kutusu', 'sensör', 'akıllı ev', 'hijyen'],
    description: 'El yaklaştığında otomatik açılan, koku sızdırmaz sensörlü çöp kutusu kapağı.',
    supplierTip: 'Sadece 2 rakip var. Alibaba 25-40 TL. Elektronik ürün, CE belgesi şart.',
  },
  {
    id: 'ozel-006',
    name: 'Mıknatıslı Bileklik (Vida Tutucu)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Giyilebilir',
    costPrice: 18,
    sellPrice: 89,
    profitMargin: 80,
    competitorCount: 1,
    monthlySearchVolume: 1900,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Amazon / Trendyol',
    tags: ['bileklik', 'mıknatıs', 'vida', 'tamir'],
    description: 'Bileğe takılan, vidaları ve küçük metal parçaları tutan mıknatıslı bileklik. Tamir işlerinde pratik.',
    supplierTip: 'Türkiye\'de neredeyse hiç satıcı yok. Alibaba 6-10 TL. İlk giren avantajı.',
  },
  {
    id: 'ozel-007',
    name: 'Kedi Su Pınarı (Filtreli, Otomatik)',
    category: 'Evcil Hayvan',
    subCategory: 'Kedi',
    costPrice: 85,
    sellPrice: 399,
    profitMargin: 79,
    competitorCount: 2,
    monthlySearchVolume: 4400,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / Amazon',
    tags: ['kedi', 'su pınarı', 'filtreli', 'otomatik'],
    description: 'Sürekli dönen, filtreli, otomatik kedi su pınarı. Kedilerin daha çok su içmesini sağlar.',
    supplierTip: 'Sadece 2 rakip. Alibaba 35-55 TL. Filtre yedekleriyle tekrar satış yapılabilir.',
  },
  {
    id: 'ozel-008',
    name: 'Silikon Ayakkabı Koruyucu (Yağmur İçin)',
    category: 'Ev & Yaşam',
    subCategory: 'Dekorasyon',
    costPrice: 22,
    sellPrice: 99,
    profitMargin: 78,
    competitorCount: 2,
    monthlySearchVolume: 2700,
    trend: 'stable',
    seasonality: 'winter',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['ayakkabı', 'yağmur', 'silikon', 'koruyucu'],
    description: 'Ayakkabının üzerine giyilen, yağmura ve çamura karşı koruyan silikon kılıf.',
    supplierTip: 'Alibaba 8-12 TL. Kış aylarında talep artar.',
  },
  {
    id: 'ozel-009',
    name: 'Araç İçi Mini Klima Fanı (Buz Hazneli)',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Aksesuar',
    costPrice: 58,
    sellPrice: 279,
    profitMargin: 79,
    competitorCount: 1,
    monthlySearchVolume: 2300,
    trend: 'rising',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['araba', 'klima', 'fan', 'yaz'],
    description: 'Buz haznesi olan, araç içine yerleştirilen mini klima fanı. Yaz aylarında serinletir.',
    supplierTip: 'Sadece 1 rakip! Alibaba 25-35 TL. Yaz sezonunda patlama yapar.',
  },
  {
    id: 'ozel-010',
    name: 'Akıllı Tohum Starter Seti (LED Grow Light)',
    category: 'Ev & Yaşam',
    subCategory: 'Bahçe',
    costPrice: 75,
    sellPrice: 349,
    profitMargin: 78,
    competitorCount: 2,
    monthlySearchVolume: 3100,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Amazon / Trendyol',
    tags: ['bahçe', 'tohum', 'led', 'kendin yetiştir'],
    description: 'LED grow light ile kapalı alanda bitki yetiştirmeye yarayan akıllı starter seti.',
    supplierTip: 'Sadece 2 rakip. Alibaba 30-50 TL. Evde bitki yetiştirme trendinde.',
  },

  // ============ BÜYÜK EKLEME - EV & YAŞAM ============
  {
    id: 'ev-013',
    name: 'Mutfak Tezgahı Kenar Sıçrama Koruyucu (Şeffaf)',
    category: 'Ev & Yaşam',
    subCategory: 'Mutfak Gereçleri',
    costPrice: 15,
    sellPrice: 69,
    profitMargin: 78,
    competitorCount: 3,
    monthlySearchVolume: 2500,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['mutfak', 'koruyucu', 'tezgah', 'pratik'],
    description: 'Ocak ile tezgah arasındaki boşluğu kapatan, sıvı sıçramasını önleyen şeffaf silikon şerit.',
    supplierTip: 'Alibaba 1-3 TL/metre. Çok düşük maliyet, toplu satış ideal.',
  },
  {
    id: 'ev-014',
    name: 'Buzdolabı Koku Giderici (Aktif Karbon)',
    category: 'Ev & Yaşam',
    subCategory: 'Organizasyon',
    costPrice: 9,
    sellPrice: 49,
    profitMargin: 82,
    competitorCount: 4,
    monthlySearchVolume: 3200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['buzdolabı', 'koku', 'aktif karbon', 'temizlik'],
    description: 'Buzdolabındaki kötü kokuları emen, ayda bir yenilenen aktif karbon kutu.',
    supplierTip: 'Alibaba 1-2 TL. Markalı ambalajla 5x kâr yapılabilir.',
  },
  {
    id: 'ev-015',
    name: 'Silikon Gömlek Yaka Koruyucu (Makyaj İçin)',
    category: 'Ev & Yaşam',
    subCategory: 'Banyo',
    costPrice: 11,
    sellPrice: 59,
    profitMargin: 81,
    competitorCount: 2,
    monthlySearchVolume: 1900,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['makyaj', 'gömlek', 'koruyucu', 'silikon'],
    description: 'Makyaj yaparken gömlek yakasını lekelemeyi önleyen, boyuna takılan silikon koruyucu.',
    supplierTip: 'Alibaba 2-4 TL. Çok az rakip, viral olabilir.',
  },
  {
    id: 'ev-016',
    name: 'Kendinden Yapışkanlı Mermer Desenli Folyo',
    category: 'Ev & Yaşam',
    subCategory: 'Dekorasyon',
    costPrice: 25,
    sellPrice: 119,
    profitMargin: 79,
    competitorCount: 5,
    monthlySearchVolume: 5400,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['dekorasyon', 'folyo', 'mermer', 'kendin yap'],
    description: 'Mutfak tezgahı ve mobilyaları mermer görünümüne kavuşturan yapışkanlı folyo.',
    supplierTip: 'Alibaba 5-10 TL/metre. Trend desenler hızlı satar.',
  },
  {
    id: 'ev-017',
    name: 'Mini Hava Nemlendirici (USB, 300ml)',
    category: 'Ev & Yaşam',
    subCategory: 'Dekorasyon',
    costPrice: 35,
    sellPrice: 159,
    profitMargin: 78,
    competitorCount: 6,
    monthlySearchVolume: 6800,
    trend: 'stable',
    seasonality: 'winter',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['nemlendirici', 'usb', 'ofis', 'kış'],
    description: 'USB ile çalışan, 7 renk LED li, sessiz mini hava nemlendirici.',
    supplierTip: 'Alibaba 12-20 TL. Kış sezonunda talep yüksek.',
  },
  {
    id: 'ev-018',
    name: 'Banyo Küvet Telefon Tutucu (Su Geçirmez)',
    category: 'Ev & Yaşam',
    subCategory: 'Banyo',
    costPrice: 18,
    sellPrice: 89,
    profitMargin: 80,
    competitorCount: 3,
    monthlySearchVolume: 4100,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['banyo', 'telefon', 'küvet', 'su geçirmez'],
    description: 'Küvet kenarına yapışan, su geçirmez telefon tutucu. Banyoda film izlemek için.',
    supplierTip: 'Alibaba 6-10 TL. Eğlenceli ürün, sosyal medyada viral.',
  },
  {
    id: 'ev-019',
    name: 'Dolap İçi LED Şerit (Hareket Sensörlü)',
    category: 'Ev & Yaşam',
    subCategory: 'Aydınlatma',
    costPrice: 22,
    sellPrice: 99,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 4700,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['dolap', 'led', 'hareket sensörü', 'aydınlatma'],
    description: 'Dolap açıldığında otomatik yanan, pilli LED şerit. Kablo gerektirmez.',
    supplierTip: 'Alibaba 7-12 TL. Mutfak dolaplarında çok kullanılır.',
  },
  {
    id: 'ev-020',
    name: 'Silikon Gözyaşı Damlalık (Soğuk Algınlığı)',
    category: 'Ev & Yaşam',
    subCategory: 'Banyo',
    costPrice: 8,
    sellPrice: 45,
    profitMargin: 82,
    competitorCount: 1,
    monthlySearchVolume: 1500,
    trend: 'stable',
    seasonality: 'winter',
    difficulty: 'easy',
    source: 'Trendyol / Eczane tarzı',
    tags: ['göz', 'damlalık', 'sağlık', 'silikon'],
    description: 'Gözyaşı damlası veya ilaç damlatmak için kullanılan, yumuşak silikon aplikatör.',
    supplierTip: 'Türkiye\'de neredeyse hiç satıcı yok. Alibaba 1-3 TL.',
  },

  // ============ BÜYÜK EKLEME - ANNE & BEBEK ============
  {
    id: 'bebek-008',
    name: 'Bebek Saç Tarama Eldiveni (Silikon)',
    category: 'Anne & Bebek',
    subCategory: 'Beslenme',
    costPrice: 14,
    sellPrice: 69,
    profitMargin: 80,
    competitorCount: 3,
    monthlySearchVolume: 2800,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['bebek', 'saç', 'tarağı', 'silikon'],
    description: 'Bebeklerin hassas saçlarını açan, baş derisini masaj eden silikon eldiven.',
    supplierTip: 'Alibaba 3-6 TL. Banyo seti içinde satılabilir.',
  },
  {
    id: 'bebek-009',
    name: 'Bebek Yürüme Kemiği (Kumaş)',
    category: 'Anne & Bebek',
    subCategory: 'Güvenlik',
    costPrice: 38,
    sellPrice: 169,
    profitMargin: 77,
    competitorCount: 4,
    monthlySearchVolume: 3600,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['bebek', 'yürüme', 'kemiği', 'destek'],
    description: 'Bebeklerin ilk adımlarında dengesini sağlayan, yumuşak kumaş yürüme kemiği.',
    supplierTip: 'Alibaba 12-18 TL. Nefes alan kumaş tercih edin.',
  },
  {
    id: 'bebek-010',
    name: 'Bebek Uyku Çıngıraklığı (Beyaz Gürültü)',
    category: 'Anne & Bebek',
    subCategory: 'Bebek Odası',
    costPrice: 42,
    sellPrice: 189,
    profitMargin: 78,
    competitorCount: 3,
    monthlySearchVolume: 3300,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Anne Bebek Siteleri',
    tags: ['bebek', 'uyku', 'beyaz gürültü', 'çıngırak'],
    description: 'Bebekleri rahatlatan beyaz gürültü ve yumuşak ışık çıngıraklık.',
    supplierTip: 'Alibaba 15-25 TL. USB şarjlı modeller tercih edin.',
  },
  {
    id: 'bebek-011',
    name: 'Bebek Emzik Zinciri (Kişiselleştirilebilir)',
    category: 'Anne & Bebek',
    subCategory: 'Beslenme',
    costPrice: 12,
    sellPrice: 59,
    profitMargin: 80,
    competitorCount: 5,
    monthlySearchVolume: 4200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hediyelik',
    tags: ['bebek', 'emzik', 'zincir', 'kişiselleştirme'],
    description: 'Ahşap boncuklu, isim yazılabilen bebek emzik zinciri.',
    supplierTip: 'Alibaba 3-6 TL. İsim baskısıyla kâr artırılabilir.',
  },
  {
    id: 'bebek-012',
    name: 'Bebek Banyo Filesi (Yeni Doğan)',
    category: 'Anne & Bebek',
    subCategory: 'Banyo',
    costPrice: 16,
    sellPrice: 79,
    profitMargin: 80,
    competitorCount: 4,
    monthlySearchVolume: 3100,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['bebek', 'banyo', 'file', 'yeni doğan'],
    description: 'Küvet içinde bebeği destekleyen, kaydırmaz banyo filesi.',
    supplierTip: 'Alibaba 5-9 TL. Standartlara uygun malzeme seçin.',
  },

  // ============ BÜYÜK EKLEME - SPOR & OUTDOOR ============
  {
    id: 'spor-009',
    name: 'Elastik Spor Egzersiz Matı (Taşınabilir)',
    category: 'Spor & Outdoor',
    subCategory: 'Fitness',
    costPrice: 32,
    sellPrice: 149,
    profitMargin: 78,
    competitorCount: 5,
    monthlySearchVolume: 5200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['fitness', 'mat', 'yoga', 'spor'],
    description: 'Kaymaz, 6mm kalınlıkta, taşıma askılı yoga ve pilates matı.',
    supplierTip: 'Alibaba 10-18 TL. Farklı renk ve desenlerle satın.',
  },
  {
    id: 'spor-010',
    name: 'Kamp Sandalyesi (Ultra Hafif)',
    category: 'Spor & Outdoor',
    subCategory: 'Kamp',
    costPrice: 65,
    sellPrice: 289,
    profitMargin: 77,
    competitorCount: 4,
    monthlySearchVolume: 6100,
    trend: 'rising',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['kamp', 'sandalye', 'hafif', 'outdoor'],
    description: 'Katlanabilir, çantaya sığan, ultra hafif kamp sandalyesi.',
    supplierTip: 'Alibaba 25-40 TL. Yaz sezonunda stok tutun.',
  },
  {
    id: 'spor-011',
    name: 'Bisiklet Arka Çanta (Su Geçirmez)',
    category: 'Spor & Outdoor',
    subCategory: 'Bisiklet',
    costPrice: 45,
    sellPrice: 199,
    profitMargin: 77,
    competitorCount: 3,
    monthlySearchVolume: 3800,
    trend: 'stable',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['bisiklet', 'çanta', 'su geçirmez', 'spor'],
    description: 'Bisiklet sele altına takılan, su geçirmez, yansıtıcı şeritli kargo çantası.',
    supplierTip: 'Alibaba 15-25 TL. Yansıtıcı detaylar önemli.',
  },
  {
    id: 'spor-012',
    name: 'Koşu Diz Bandı (Sıkıştırıcı)',
    category: 'Spor & Outdoor',
    subCategory: 'Koşu',
    costPrice: 19,
    sellPrice: 89,
    profitMargin: 79,
    competitorCount: 5,
    monthlySearchVolume: 4300,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['koşu', 'diz', 'bandı', 'spor'],
    description: 'Koşu ve spor sırasında diz desteği sağlayan, nefes alabilir sıkıştırıcı band.',
    supplierTip: 'Alibaba 6-12 TL. Sporcu kitlesine hedefleyin.',
  },
  {
    id: 'spor-013',
    name: 'Şnorkel Seti (Maske + Şnorkel)',
    category: 'Spor & Outdoor',
    subCategory: 'Su Sporları',
    costPrice: 55,
    sellPrice: 249,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 7200,
    trend: 'stable',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['şnorkel', 'maske', 'deniz', 'yaz'],
    description: 'Yüzme ve şnorkelleme için tam yüz maskesi ve şnorkel seti.',
    supplierTip: 'Alibaba 20-35 TL. Yaz sezonunda patlar.',
  },

  // ============ BÜYÜK EKLEME - EVCİL HAYVAN ============
  {
    id: 'pet-008',
    name: 'Kedi Tüy Toplama Eldiveni (Silikon)',
    category: 'Evcil Hayvan',
    subCategory: 'Kedi',
    costPrice: 15,
    sellPrice: 69,
    profitMargin: 78,
    competitorCount: 5,
    monthlySearchVolume: 5400,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['kedi', 'tüy', 'eldiven', 'silikon'],
    description: 'Eldiven şeklinde, kedi tüylerini toplayan ve masaj yapan silikon eldiven.',
    supplierTip: 'Alibaba 4-8 TL. Evcil hayvan seti içinde satılabilir.',
  },
  {
    id: 'pet-009',
    name: 'Köpek Eğitim Clicker Seti (3\'lü)',
    category: 'Evcil Hayvan',
    subCategory: 'Köpek',
    costPrice: 12,
    sellPrice: 59,
    profitMargin: 80,
    competitorCount: 2,
    monthlySearchVolume: 2600,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['köpek', 'eğitim', 'clicker', 'set'],
    description: 'Köpek eğitiminde kullanılan, bileğe takılabilir 3\'lü clicker seti.',
    supplierTip: 'Alibaba 2-5 TL. Eğitim kitapçığıyla birlikte satılabilir.',
  },
  {
    id: 'pet-010',
    name: 'Kedi Oyun Tüneli (Katlanabilir)',
    category: 'Evcil Hayvan',
    subCategory: 'Kedi',
    costPrice: 28,
    sellPrice: 129,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 4800,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['kedi', 'tünel', 'oyun', 'katlanabilir'],
    description: 'Katlanabilir, dayanıklı kumaş kedi oyun tüneli. Toplu eğlence seti.',
    supplierTip: 'Alibaba 10-18 TL. Kedi oyuncağı setiyle kombinleyin.',
  },
  {
    id: 'pet-011',
    name: 'Akvaryum Sifon (Kum Temizleyici)',
    category: 'Evcil Hayvan',
    subCategory: 'Akvaryum',
    costPrice: 18,
    sellPrice: 89,
    profitMargin: 80,
    competitorCount: 3,
    monthlySearchVolume: 2900,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['akvaryum', 'sifon', 'temizlik', 'balık'],
    description: 'Akvaryum dibindeki kumu ve tortuyu kolayca temizleyen manuel sifon.',
    supplierTip: 'Alibaba 6-10 TL. Balık tutkunlarına hitap eder.',
  },

  // ============ BÜYÜK EKLEME - HOBİ & EL SANATLARI ============
  {
    id: 'hobi-007',
    name: 'Alkol Mürekkep Seti (24 Renk + Fırça)',
    category: 'Hobi & El Sanatları',
    subCategory: 'Resim',
    costPrice: 35,
    sellPrice: 159,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 3900,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['resim', 'mürekkep', 'alkol', 'sanat'],
    description: '24 renk alkol mürekkebi, blending çözücüsü ve fırça seti. Suluboya efektleri için.',
    supplierTip: 'Alibaba 12-20 TL. Sanatçı kitlesine hedefleyin.',
  },
  {
    id: 'hobi-008',
    name: 'Makrome Duvar Süsü Seti (Kendin Yap)',
    category: 'Hobi & El Sanatları',
    subCategory: 'Örgü',
    costPrice: 28,
    sellPrice: 129,
    profitMargin: 78,
    competitorCount: 3,
    monthlySearchVolume: 5100,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / Etsy tarzı siteler',
    tags: ['makrome', 'duvar süsü', 'kendin yap', 'dekorasyon'],
    description: 'Makrome duvar süsü yapmak için ip, ahşap çubuk ve video talimat seti.',
    supplierTip: 'Alibaba 10-18 TL. Boho dekorasyon trendinde.',
  },
  {
    id: 'hobi-009',
    name: 'Model Araba Boyama Seti (Airbrush)',
    category: 'Hobi & El Sanatları',
    subCategory: 'Modelleme',
    costPrice: 55,
    sellPrice: 249,
    profitMargin: 78,
    competitorCount: 2,
    monthlySearchVolume: 2200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / Amazon',
    tags: ['model', 'araba', 'boyama', 'hobi'],
    description: 'Mini airbrush tabancası, boyalar ve model araba içeren boyama seti.',
    supplierTip: 'Alibaba 20-35 TL. Hobi tutkunlarına yönelik niş ürün.',
  },
  {
    id: 'hobi-010',
    name: 'Reçine Saat Yapım Kiti',
    category: 'Hobi & El Sanatları',
    subCategory: 'Takı Yapımı',
    costPrice: 42,
    sellPrice: 189,
    profitMargin: 78,
    competitorCount: 2,
    monthlySearchVolume: 1800,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / Etsy tarzı siteler',
    tags: ['reçine', 'saat', 'kendin yap', 'hediye'],
    description: 'Epoksi reçine ile kendi saatini yapma seti. Mekanizma, kalıp ve boyalar dahil.',
    supplierTip: 'Alibaba 15-25 TL. Hediye olarak konumlandırılabilir.',
  },

  // ============ BÜYÜK EKLEME - TEKNOLOJİ & AKSESUAR ============
  {
    id: 'tech-009',
    name: 'Telefon Ekran Büyüteci (3D)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Telefon',
    costPrice: 16,
    sellPrice: 79,
    profitMargin: 80,
    competitorCount: 4,
    monthlySearchVolume: 4700,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['telefon', 'büyüteç', 'film', 'pratik'],
    description: 'Telefon ekranını 3-4 kat büyüten, katlanabilir 3D ekran büyüteci.',
    supplierTip: 'Alibaba 5-10 TL. Film izleyen kitleye hitap eder.',
  },
  {
    id: 'tech-010',
    name: 'Laptop Soğutucu Stand (Fanlı)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Bilgisayar',
    costPrice: 48,
    sellPrice: 219,
    profitMargin: 78,
    competitorCount: 6,
    monthlySearchVolume: 5800,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['laptop', 'soğutucu', 'stand', 'fan'],
    description: '6 fanlı, RGB ışıklı, ergonomik laptop soğutucu stand.',
    supplierTip: 'Alibaba 18-30 TL. Gamer ve ofis çalışanlarına hitap eder.',
  },
  {
    id: 'tech-011',
    name: 'Kablosuz Kulaklık Kılıfı (Silikon, AirPods)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Giyilebilir',
    costPrice: 9,
    sellPrice: 49,
    profitMargin: 82,
    competitorCount: 7,
    monthlySearchVolume: 6200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['airpods', 'kılıf', 'silikon', 'aksesuar'],
    description: 'AirPods ve benzeri kulaklıklar için karakterli silikon koruyucu kılıf.',
    supplierTip: 'Alibaba 2-5 TL. Karakter tasarımlarıyla fark yaratın.',
  },
  {
    id: 'tech-012',
    name: 'USB LED Masa Lambası (Dokunmatik)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Bilgisayar',
    costPrice: 22,
    sellPrice: 99,
    profitMargin: 78,
    competitorCount: 5,
    monthlySearchVolume: 5100,
    trend: 'stable',
    seasonality: 'back-to-school',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['masa lambası', 'led', 'usb', 'okul'],
    description: 'Dokunmatik kontrollü, 3 ışık modlu, USB çalışan LED masa lambası.',
    supplierTip: 'Alibaba 8-15 TL. Okul sezonunda satış artar.',
  },
  {
    id: 'tech-013',
    name: 'Telefon Oyun Tetikleyicisi (PUBG)',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Oyun',
    costPrice: 12,
    sellPrice: 59,
    profitMargin: 80,
    competitorCount: 8,
    monthlySearchVolume: 8900,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['oyun', 'pubg', 'tetikleyici', 'telefon'],
    description: 'Mobil oyunlarda daha hızlı ateş etmeyi sağlayan L1R1 tetikleyici seti.',
    supplierTip: 'Alibaba 3-6 TL. Gamer kitleye yönelik ucuz ve hacimli ürün.',
  },

  // ============ BÜYÜK EKLEME - SAĞLIK & BAKIM ============
  {
    id: 'saglik-007',
    name: 'Siyah Nokta Temizleyici Vakum (USB)',
    category: 'Sağlık & Bakım',
    subCategory: 'Cilt Bakımı',
    costPrice: 32,
    sellPrice: 149,
    profitMargin: 78,
    competitorCount: 6,
    monthlySearchVolume: 7400,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['cilt', 'siyah nokta', 'vakum', 'bakım'],
    description: 'USB şarjlı, 4 farklı başlıklı siyah nokta ve yağ temizleyici vakum cihazı.',
    supplierTip: 'Alibaba 10-18 TL. Cilt bakım seti içinde satılabilir.',
  },
  {
    id: 'saglik-008',
    name: 'Dil Temizleyici (Paslanmaz Çelik)',
    category: 'Sağlık & Bakım',
    subCategory: 'Ağız Bakımı',
    costPrice: 9,
    sellPrice: 49,
    profitMargin: 82,
    competitorCount: 3,
    monthlySearchVolume: 3500,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['ağız', 'dil', 'temizleyici', 'çelik'],
    description: 'Paslanmaz çelik dil temizleyici. Ağız hijyenini artırır, nefesi tazeler.',
    supplierTip: 'Alibaba 2-4 TL. Ağız bakım setiyle kombinleyin.',
  },
  {
    id: 'saglik-009',
    name: 'Göz Masaj Aleti (Titreşimli)',
    category: 'Sağlık & Bakım',
    subCategory: 'Masaj',
    costPrice: 45,
    sellPrice: 199,
    profitMargin: 77,
    competitorCount: 4,
    monthlySearchVolume: 4600,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['göz', 'masaj', 'titreşim', 'rahatlama'],
    description: 'Göz çevresini masaj eden, ısıtmalı titreşimli göz masaj aleti.',
    supplierTip: 'Alibaba 15-25 TL. Ofis çalışanlarına hedefleyin.',
  },
  {
    id: 'saglik-010',
    name: 'Bambu Diş Fırçası Seti (4\'lü)',
    category: 'Sağlık & Bakım',
    subCategory: 'Ağız Bakımı',
    costPrice: 18,
    sellPrice: 89,
    profitMargin: 80,
    competitorCount: 5,
    monthlySearchVolume: 4200,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['diş fırçası', 'bambu', 'doğal', 'set'],
    description: 'Bambu saplı, doğal kıllı, çevre dostu 4\'lü diş fırçası seti.',
    supplierTip: 'Alibaba 5-10 TL. Sürdürülebilir yaşam kitleye hitap eder.',
  },

  // ============ BÜYÜK EKLEME - OTOMOTİV ============
  {
    id: 'oto-007',
    name: 'Araç İçi Tablet Tutucu (Kafalık İçin)',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Aksesuar',
    costPrice: 28,
    sellPrice: 129,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 4300,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['araba', 'tablet', 'tutucu', 'çocuk'],
    description: 'Arka kafalığa takılan, tablet ve telefon tutucu. Çocuklar için ideal.',
    supplierTip: 'Alibaba 10-18 TL. Aileler için pratik ürün.',
  },
  {
    id: 'oto-008',
    name: 'Araç İçi Toz Temizleme Jeli',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Bakım',
    costPrice: 8,
    sellPrice: 45,
    profitMargin: 82,
    competitorCount: 3,
    monthlySearchVolume: 5200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['araba', 'toz', 'temizlik', 'jel'],
    description: 'Havalandırma menfezleri ve zor alanlardaki tozu temizleyen yapışkan jel.',
    supplierTip: 'Alibaba 2-4 TL. Çok düşük maliyet, yüksek hacim.',
  },
  {
    id: 'oto-009',
    name: 'Motosiklet Eldiveni (Dokunmatik Ekran)',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Motosiklet Ekipmanı',
    costPrice: 35,
    sellPrice: 159,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 4800,
    trend: 'stable',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['motosiklet', 'eldiven', 'dokunmatik', 'yaz'],
    description: 'Dokunmatik ekran uyumlu, nefes alan, yazlık motosiklet eldiveni.',
    supplierTip: 'Alibaba 12-20 TL. Yaz sezonunda motosiklet ürünleri artar.',
  },
  {
    id: 'oto-010',
    name: 'Araç İçi Güneşlik (Manyetik)',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Aksesuar',
    costPrice: 18,
    sellPrice: 89,
    profitMargin: 80,
    competitorCount: 5,
    monthlySearchVolume: 6100,
    trend: 'stable',
    seasonality: 'summer',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['araba', 'güneşlik', 'manyetik', 'yaz'],
    description: 'Cam kenarına mıknatısla tutturulan, kolayca çıkarılabilen araç güneşliği.',
    supplierTip: 'Alibaba 6-12 TL. Yaz sezonunda stok tutun.',
  },

  // ============ BÜYÜK EKLEME - PARTİ ============
  {
    id: 'parti-005',
    name: 'Parti Konfeti Topu (4\'lü)',
    category: 'Parti & Organizasyon',
    subCategory: 'Parti Malzemeleri',
    costPrice: 14,
    sellPrice: 69,
    profitMargin: 80,
    competitorCount: 4,
    monthlySearchVolume: 3300,
    trend: 'stable',
    seasonality: 'holiday',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['parti', 'konfeti', 'doğum günü', 'eğlence'],
    description: 'Çevirdiğinde konfeti atan, 4 adet parti konfeti topu.',
    supplierTip: 'Alibaba 4-8 TL. Parti setleri içinde satılabilir.',
  },
  {
    id: 'parti-006',
    name: 'LED Işıklı Parti Gözlüğü',
    category: 'Parti & Organizasyon',
    subCategory: 'Kostüm',
    costPrice: 12,
    sellPrice: 59,
    profitMargin: 80,
    competitorCount: 3,
    monthlySearchVolume: 2800,
    trend: 'rising',
    seasonality: 'holiday',
    difficulty: 'easy',
    source: 'Trendyol / N11',
    tags: ['parti', 'gözlük', 'led', 'kostüm'],
    description: 'Yanıp sönen LED ışıklı parti gözlüğü. Yılbaşı ve kutlamalar için.',
    supplierTip: 'Alibaba 3-6 TL. Yılbaşı sezonunda patlar.',
  },
  {
    id: 'parti-007',
    name: 'Doğum Günü Mumu Seti (Sönmez)',
    category: 'Parti & Organizasyon',
    subCategory: 'Parti Malzemeleri',
    costPrice: 16,
    sellPrice: 79,
    profitMargin: 80,
    competitorCount: 4,
    monthlySearchVolume: 3600,
    trend: 'stable',
    seasonality: 'holiday',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['doğum günü', 'mum', 'sönmez', 'parti'],
    description: 'Üfleyince sönmeyen, tekrar yanan sihirli doğum günü mumu seti.',
    supplierTip: 'Alibaba 5-9 TL. Doğum günü setleriyle kombinleyin.',
  },

  // ============ BÜYÜK EKLEME - KIRTASİYE ============
  {
    id: 'kitap-006',
    name: 'Akıllı Kitap Ayracı (LED Işıklı)',
    category: 'Kitap & Kırtasiye',
    subCategory: 'Defter',
    costPrice: 12,
    sellPrice: 59,
    profitMargin: 80,
    competitorCount: 3,
    monthlySearchVolume: 2400,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['kitap', 'ayraç', 'led', 'okuma'],
    description: 'Kitap sayfasını aydınlatan, ince LED ışıklı okuma ayracı.',
    supplierTip: 'Alibaba 3-6 TL. Hediye olarak satılabilir.',
  },
  {
    id: 'kitap-007',
    name: 'Kalem Uzatma Aparatı Seti (Silikon, 10\'lu)',
    category: 'Kitap & Kırtasiye',
    subCategory: 'Kalem',
    costPrice: 8,
    sellPrice: 45,
    profitMargin: 82,
    competitorCount: 2,
    monthlySearchVolume: 1900,
    trend: 'stable',
    seasonality: 'back-to-school',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['kalem', 'uzatma', 'okul', 'set'],
    description: 'Kısalıp tutulması zorlaşan kalemleri uzatmaya yarayan silikon aparat seti.',
    supplierTip: 'Alibaba 1-3 TL. Okul sezonunda toplu satış ideal.',
  },
  {
    id: 'kitap-008',
    name: 'Not Tutma Panosu (Masaüstü, Ahşap)',
    category: 'Kitap & Kırtasiye',
    subCategory: 'Planlayıcı',
    costPrice: 32,
    sellPrice: 149,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 3100,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['masaüstü', 'pano', 'ahşap', 'organizasyon'],
    description: 'Masaüstüne konulan, not ve görev kartları asılabilen ahşap planlama panosu.',
    supplierTip: 'Alibaba 12-20 TL. Kurumsal hediye olarak satılabilir.',
  },

  // ============ BÜYÜK EKLEME - YÜKSEK KÂR ============
  {
    id: 'ozel-011',
    name: 'Akıllı Ayna (LED Işıklı, Dokunmatik)',
    category: 'Ev & Yaşam',
    subCategory: 'Dekorasyon',
    costPrice: 95,
    sellPrice: 449,
    profitMargin: 79,
    competitorCount: 2,
    monthlySearchVolume: 3800,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / Amazon',
    tags: ['ayna', 'led', 'makyaj', 'akıllı'],
    description: 'Dokunmatik kontrollü, 3 ışık modlu, büyütme özellikli akıllı makyaj aynası.',
    supplierTip: 'Sadece 2 rakip. Alibaba 40-60 TL. Elektronik ürün, CE belgesi şart.',
  },
  {
    id: 'ozel-012',
    name: 'Kablosuz Kulak Temizleme Endoskopu',
    category: 'Sağlık & Bakım',
    subCategory: 'Ağız Bakımı',
    costPrice: 55,
    sellPrice: 259,
    profitMargin: 79,
    competitorCount: 1,
    monthlySearchVolume: 2600,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Amazon / Trendyol',
    tags: ['kulak', 'endoskop', 'kablosuz', 'temizlik'],
    description: 'Wi-Fi ile telefona bağlanan, kulak içini gösteren kamera ve temizleme seti.',
    supplierTip: 'Türkiye\'de 1 rakip var. Alibaba 20-35 TL. Medikal CE şart.',
  },
  {
    id: 'ozel-013',
    name: 'Araç İçi Hava Temizleyici (İyonizer)',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Aksesuar',
    costPrice: 68,
    sellPrice: 329,
    profitMargin: 79,
    competitorCount: 2,
    monthlySearchVolume: 2900,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['araba', 'hava temizleyici', 'iyonizer', 'koku'],
    description: 'Araç içi hava kirliliğini ve kokuları gideren negatif iyon üreten cihaz.',
    supplierTip: 'Sadece 2 rakip. Alibaba 25-40 TL. CE belgeli olmalı.',
  },
  {
    id: 'ozel-014',
    name: 'Akıllı Evcil Hayvan Su Kabı (Filtreli)',
    category: 'Evcil Hayvan',
    subCategory: 'Kedi',
    costPrice: 72,
    sellPrice: 349,
    profitMargin: 79,
    competitorCount: 2,
    monthlySearchVolume: 3300,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'medium',
    source: 'Trendyol / Amazon',
    tags: ['kedi', 'köpek', 'su kabı', 'filtreli'],
    description: 'Sürekli dolaşan, filtreli, sessiz akıllı evcil hayvan su kabı.',
    supplierTip: 'Sadece 2 rakip. Alibaba 30-50 TL. Filtre yedekleri tekrar satış.',
  },
  {
    id: 'ozel-015',
    name: 'Portatif Çamaşır Kurutma Makinesi (Katlanabilir)',
    category: 'Ev & Yaşam',
    subCategory: 'Organizasyon',
    costPrice: 85,
    sellPrice: 399,
    profitMargin: 79,
    competitorCount: 1,
    monthlySearchVolume: 2400,
    trend: 'rising',
    seasonality: 'winter',
    difficulty: 'medium',
    source: 'Amazon / Trendyol',
    tags: ['çamaşır', 'kurutma', 'katlanabilir', 'kış'],
    description: 'Küçük alanlarda kullanılan, katlanabilir, elektrikli çamaşır kurutma dolabı.',
    supplierTip: 'Türkiye\'de 1 rakip. Alibaba 35-55 TL. Kış sezonunda fırsat.',
  },
  {
    id: 'ozel-016',
    name: 'Akıllı Diş Fırçası Sterilizatörü',
    category: 'Sağlık & Bakım',
    subCategory: 'Ağız Bakımı',
    costPrice: 48,
    sellPrice: 229,
    profitMargin: 79,
    competitorCount: 2,
    monthlySearchVolume: 2200,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Amazon',
    tags: ['diş fırçası', 'sterilizatör', 'uv', 'hijyen'],
    description: 'UV ışıkla diş fırçalarını sterilize eden, duvara monte edilebilir cihaz.',
    supplierTip: 'Sadece 2 rakip. Alibaba 18-30 TL. Ailelere yönelik.',
  },
  {
    id: 'ozel-017',
    name: 'Motosiklet Kask İçin Bluetooth İletişim Seti',
    category: 'Otomotiv & Motosiklet',
    subCategory: 'Motosiklet Ekipmanı',
    costPrice: 120,
    sellPrice: 549,
    profitMargin: 78,
    competitorCount: 2,
    monthlySearchVolume: 3100,
    trend: 'rising',
    seasonality: 'summer',
    difficulty: 'medium',
    source: 'Amazon / Trendyol',
    tags: ['motosiklet', 'kask', 'bluetooth', 'iletişim'],
    description: 'Kaska takılan, telefon görüşmesi ve müzik dinlemeye yarayan Bluetooth iletişim seti.',
    supplierTip: 'Sadece 2 rakip. Alibaba 50-80 TL. Yaz sezonunda motosikletçilere hitap eder.',
  },
  {
    id: 'ozel-018',
    name: 'Akıllı Mutfak Tartısı (Bluetooth)',
    category: 'Ev & Yaşam',
    subCategory: 'Mutfak Gereçleri',
    costPrice: 42,
    sellPrice: 199,
    profitMargin: 79,
    competitorCount: 3,
    monthlySearchVolume: 3500,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['mutfak', 'tartı', 'bluetooth', 'akıllı'],
    description: 'Telefona bağlanan, besin değerlerini hesaplayan akıllı mutfak tartısı.',
    supplierTip: 'Alibaba 15-25 TL. Sağlıklı yaşam kitleye hitap eder.',
  },
  {
    id: 'ozel-019',
    name: 'Kablosuz Kulaklık Temizleme Kiti',
    category: 'Teknoloji & Aksesuar',
    subCategory: 'Giyilebilir',
    costPrice: 15,
    sellPrice: 79,
    profitMargin: 81,
    competitorCount: 1,
    monthlySearchVolume: 1800,
    trend: 'rising',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Amazon / Trendyol',
    tags: ['kulaklık', 'temizlik', 'airpods', 'kit'],
    description: 'AirPods ve kulaklıkları temizlemek için özel fırça, jel ve pamuk seti.',
    supplierTip: 'Türkiye\'de 1 rakip. Alibaba 4-8 TL. Çok düşük maliyet.',
  },
  {
    id: 'ozel-020',
    name: 'Akıllı Banyo Tartısı (Vücut Analizli)',
    category: 'Sağlık & Bakım',
    subCategory: 'Cilt Bakımı',
    costPrice: 55,
    sellPrice: 249,
    profitMargin: 78,
    competitorCount: 4,
    monthlySearchVolume: 6200,
    trend: 'stable',
    seasonality: 'none',
    difficulty: 'easy',
    source: 'Trendyol / Hepsiburada',
    tags: ['banyo', 'tartı', 'vücut analizi', 'akıllı'],
    description: 'Telefona bağlanan, yağ oranı, kas kütlesi ölçen akıllı banyo tartısı.',
    supplierTip: 'Alibaba 20-35 TL. Sağlıklı yaşam kitleye yönelik.',
  },
];

// Her ürün için niş puanını hesapla
export const nicheProducts: NicheProduct[] = rawProducts.map((product) => ({
  ...product,
  nicheScore: calculateNicheScore({
    profitMargin: product.profitMargin / 100,
    competitorCount: product.competitorCount,
    monthlySearchVolume: product.monthlySearchVolume,
    trend: product.trend,
    seasonality: product.seasonality,
    difficulty: product.difficulty,
  }),
}));

// Varsayılan olarak niş puanına göre sırala (yüksekten düşüğe)
export const sortedByScore = [...nicheProducts].sort((a, b) => b.nicheScore - a.nicheScore);

// Kategorilere göre gruplandırılmış ürünler
export function getProductsByCategory(category: string): NicheProduct[] {
  return nicheProducts.filter((p) => p.category === category);
}

// Altın niş ürünler (puan >= 80)
export function getGoldenNiches(): NicheProduct[] {
  return nicheProducts.filter((p) => p.nicheScore >= 80);
}